const a = [
  {
    name: "Hue City",
    local_names: {
      de: "Hue",
      uz: "Xyue",
      ka: "ჰუე",
      bg: "Хюе",
      fa: "هوئه",
      th: "เว้",
      en: "Hue City",
      ru: "Хюэ",
      ga: "Hué",
      eo: "Hue",
      ko: "후에",
      ja: "フエ",
      mk: "Хуе",
      es: "Hué",
      eu: "Hue",
      mn: "Хюэ",
      sr: "Хуе",
      vi: "Thành phố Huế",
      el: "Χουέ",
      cs: "Hue",
      lt: "Hujė",
      uk: "Хюе",
      da: "Hué",
      kl: "Hue",
      he: "הואה",
      fr: "Hué",
      zh: "顺化市",
      ur: "ہوائے",
    },
    lat: 16.4639321,
    lon: 107.5863388,
    country: "VN",
    state: "Thừa Thiên Huế Province",
  },
  {
    name: "Hue",
    lat: 49.0304753,
    lon: -0.4292822,
    country: "FR",
    state: "Normandy",
  },
  {
    name: "Hue",
    lat: 39.3870124,
    lon: -82.5051573,
    country: "US",
    state: "Ohio",
  },
];
